Update build_packages.yml

diff --git a/.github/workflows/build_packages.yml b/.github/workflows/build_packages.yml
--- a/.github/workflows/build_packages.yml
+++ b/.github/workflows/build_packages.yml
@@ -91,52 +91,52 @@ jobs:
           ${BRANCH_SERVER//\//}" | head -n1)
           echo "PRODUCT_VERSION=${PRODUCT_VERSION:-3.1.1}" >> $GITHUB_ENV
 
-      - name: Free Disk Space
-        run: |
-          curl -fsSL https://raw.githubusercontent.com/apache/arrow/refs/heads/main/ci/scripts/util_free_space.sh | bash
-          sudo docker image prune --all --force
+      # - name: Free Disk Space
+      #   run: |
+      #     curl -fsSL https://raw.githubusercontent.com/apache/arrow/refs/heads/main/ci/scripts/util_free_space.sh | bash
+      #     sudo docker image prune --all --force
 
-      - name: Import GPG
-        uses: crazy-max/ghaction-import-gpg@v6
-        id: gpg_step
-        with:
-          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
-          passphrase: ${{ secrets.GPG_PRIVATE_KEY_PASS }}
+      # - name: Import GPG
+      #   uses: crazy-max/ghaction-import-gpg@v6
+      #   id: gpg_step
+      #   with:
+      #     gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
+      #     passphrase: ${{ secrets.GPG_PRIVATE_KEY_PASS }}
 
-      - name: Prepare build
-        run: |
-          wget -O - https://dl.yarnpkg.com/debian/pubkey.gpg | \
-          sudo gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/yarnkey.gpg --import
-          sudo chmod 644 /usr/share/keyrings/yarnkey.gpg
-          echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian/ stable main" | \
-          sudo tee /etc/apt/sources.list.d/yarn.list
-          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo bash -
-          sudo apt install -y dotnet-sdk-9.0 yarn nodejs rename unzip maven openjdk-21-jdk-headless
-          JAVA_PATH=$(find /usr/lib/jvm/ -name "java" -path "*java-${JAVA_VERSION}*" | head -1)
-          sudo update-alternatives --install /usr/bin/java java "$JAVA_PATH" 100 && sudo update-alternatives --set java "$JAVA_PATH"
-          echo "JAVA_HOME=$(dirname $(dirname "$JAVA_PATH"))" >> $GITHUB_ENV
-          sudo npm install -g json
-          if [[ "${{ matrix.packageType }}" == "rpm" ]]; then
-            sudo apt install -y python3-rpm python3-pip
-            sudo pip install rpmlint
-          else
-            sudo apt install -y dpkg-sig lintian dh-make
-          fi
+      # - name: Prepare build
+      #   run: |
+      #     wget -O - https://dl.yarnpkg.com/debian/pubkey.gpg | \
+      #     sudo gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/yarnkey.gpg --import
+      #     sudo chmod 644 /usr/share/keyrings/yarnkey.gpg
+      #     echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian/ stable main" | \
+      #     sudo tee /etc/apt/sources.list.d/yarn.list
+      #     curl -fsSL https://deb.nodesource.com/setup_20.x | sudo bash -
+      #     sudo apt install -y dotnet-sdk-9.0 yarn nodejs rename unzip maven openjdk-21-jdk-headless
+      #     JAVA_PATH=$(find /usr/lib/jvm/ -name "java" -path "*java-${JAVA_VERSION}*" | head -1)
+      #     sudo update-alternatives --install /usr/bin/java java "$JAVA_PATH" 100 && sudo update-alternatives --set java "$JAVA_PATH"
+      #     echo "JAVA_HOME=$(dirname $(dirname "$JAVA_PATH"))" >> $GITHUB_ENV
+      #     sudo npm install -g json
+      #     if [[ "${{ matrix.packageType }}" == "rpm" ]]; then
+      #       sudo apt install -y python3-rpm python3-pip
+      #       sudo pip install rpmlint
+      #     else
+      #       sudo apt install -y dpkg-sig lintian dh-make
+      #     fi
 
-      - name: Download sources
-        run: |
-          case "${{ matrix.packageType }}" in
-            deb) SOURCE_DIR="${PACKAGE_DIRECTORY}/install/${{ matrix.packageType }}/debian/source" ;;
-            rpm) SOURCE_DIR="${PACKAGE_DIRECTORY}/install/${{ matrix.packageType }}/SPECS/SOURCES" ;;
-          esac
-          download() { wget -q -O "${SOURCE_DIR}/$3.tar.gz" "https://github.com/ONLYOFFICE/$1/archive/$2.tar.gz" && echo -e "\e[32m[OK] $3\e[0m" || echo -e "\e[31m[FAILED] $3\e[0m"; }
-          download "$PRODUCT-buildtools"  "$BRANCH_BUILDTOOLS"      buildtools &
-          download "$PRODUCT-client"      "$BRANCH_CLIENT"          client &
-          download "$PRODUCT-server"      "$BRANCH_SERVER"          server &
-          download "document-templates"   "main/community-server"   DocStore &
-          download "ASC.Web.Campaigns"    "master"                  campaigns &
-          download "$PRODUCT-plugins"     "master"                  plugins &
-          wait
+      # - name: Download sources
+      #   run: |
+      #     case "${{ matrix.packageType }}" in
+      #       deb) SOURCE_DIR="${PACKAGE_DIRECTORY}/install/${{ matrix.packageType }}/debian/source" ;;
+      #       rpm) SOURCE_DIR="${PACKAGE_DIRECTORY}/install/${{ matrix.packageType }}/SPECS/SOURCES" ;;
+      #     esac
+      #     download() { wget -q -O "${SOURCE_DIR}/$3.tar.gz" "https://github.com/ONLYOFFICE/$1/archive/$2.tar.gz" && echo -e "\e[32m[OK] $3\e[0m" || echo -e "\e[31m[FAILED] $3\e[0m"; }
+      #     download "$PRODUCT-buildtools"  "$BRANCH_BUILDTOOLS"      buildtools &
+      #     download "$PRODUCT-client"      "$BRANCH_CLIENT"          client &
+      #     download "$PRODUCT-server"      "$BRANCH_SERVER"          server &
+      #     download "document-templates"   "main/community-server"   DocStore &
+      #     download "ASC.Web.Campaigns"    "master"                  campaigns &
+      #     download "$PRODUCT-plugins"     "master"                  plugins &
+      #     wait
 
       # - name: Build DEB Packages
       #   if: matrix.packageType == 'deb'
